export const LOAD_FLIGHTS_SUCCESS = 'LOAD_FLIGHTS_SUCCESS';
export const ADD_FLIGHT_SUCCESS = 'ADD_FLIGHT_SUCCESS';
export const ADD_STOP_SUCCESS = 'ADD_STOP_SUCCESS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';