export const LOAD_FLIGHTS_SUCCESS = 'LOAD_FLIGHTS_SUCCESS';
export const LOAD_LAST_FLIGHT_SUCCESS = 'LOAD_LAST_FLIGHT_SUCCESS';
export const ADD_FLIGHT_SUCCESS = 'ADD_FLIGHT_SUCCESS';
export const ADD_STOP_SUCCESS = 'ADD_STOP_SUCCESS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';